name: Mirroring

on:
  push:
    branches:
      - master

jobs:
  to_github_public:
    runs-on: ubuntu-latest
    steps:                                              # <-- must use actions/checkout before mirroring!
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Removing .github
        run: |
          ls -la
          rm -rf .github
          ls -la
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:dorsharabi1/dor-dest-public.git
          ssh_private_key:                              # <-- use 'secrets' to pass credential information.
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}